language: python
python:
 - 2.6
 - 2.7
 - 3.2
 - 3.3

install:
  - pip install -qr requirements-test.txt
  - pip install -q coverage coveralls
  - pip install .

script:
  - nosetests

after_success:
  - coverage report
  - coveralls
